# Generated by Django 6.0.3 on 2026-03-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DialysisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("patient_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                ("weight", models.FloatField()),
                ("dry_weight", models.FloatField()),
                ("dialysis_time", models.FloatField()),
                ("uf", models.FloatField()),
                ("rate", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
