# Generated by Django 6.0.3 on 2026-03-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dialysis", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dialysisrecord",
            old_name="dialysis_time",
            new_name="dw",
        ),
        migrations.RenameField(
            model_name="dialysisrecord",
            old_name="dry_weight",
            new_name="time",
        ),
    ]
